### ISSUE TITLE
I have this error in my nextjs app

### ISSUE THREAD

**Issue by asenseofpradhyu** [LuanEdCosta/copy-image-clipboard#31]
![Screenshot 2022-05-12 at 8 53 33 PM](https://user-images.githubusercontent.com/24241624/168110952-06670285-e92e-452f-8236-9f7b98224b86.png)

Please help here.. How to solve this error?

**Comment by LuanEdCosta** [comment]
It seems that NextJS is trying to import using CommonJS (require, module.exports), but this library exports everything using ES modules (import/export).

I found some StackOverflow links that may help you:
- https://stackoverflow.com/questions/65936222/next-js-syntaxerror-unexpected-token-export
- https://stackoverflow.com/questions/64847988/babylonjs-es6-in-nextjs-failes-with-unexpected-token-export
- https://stackoverflow.com/questions/69377638/nextjs-syntaxerror-unexpected-token-export

I will also try to simulate the problem later to find a nice solution and update docs.

**Comment by LuanEdCosta** [comment]
I found something interesting...

- NextJS 12.x.x supports ES modules by default. https://nextjs.org/blog/next-12#es-modules-support-and-url-imports
- NextJS 11.x.x also supports ES modules, but under an experimental flag. https://nextjs.org/blog/next-11-1#es-modules-support

I believe that updating NextJS version should fix the problem.

**Comment by asenseofpradhyu** [comment]
Hey

This link works -> https://stackoverflow.com/questions/65936222/next-js-syntaxerror-unexpected-token-export

I use the next-transpile-module package (https://github.com/martpie/next-transpile-modules#readme).

Thank You for your support...❤️
