### ISSUE TITLE
Does not work in Firefox

### ISSUE THREAD

**Issue by sdudnic** [LuanEdCosta/copy-image-clipboard#36]
The example https://luanedcosta.github.io/copy-image-clipboard/ does not work in Firefox, we obtain the message 

> ClipboardItem is not defined

**Browsers (please complete the following information)**

Browser name: Firefox (Windows)
Version: 103.0.2 (64-bit)

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/35489219/184213846-78948ea9-94ec-418e-953e-34047dd28397.png)

**Comment by LuanEdCosta** [comment]
Hi @sdudnic, thanks for creating this issue.

I've already documented this problem [here](https://github.com/LuanEdCosta/copy-image-clipboard#enable-clipboard-api-features-in-firefox).

---

You have to visit `about:config` and set `dom.events.asyncClipboard.clipboardItem` to `true`.

![image](https://user-images.githubusercontent.com/36794274/184440553-f5f46dd6-ca52-4dfe-ba88-c1f3555856fb.png)

**Comment by sdudnic** [comment]
> Hi @sdudnic, thanks for creating this issue.
> 
> I've already documented this problem [here](https://github.com/LuanEdCosta/copy-image-clipboard#enable-clipboard-api-features-in-firefox).
> 
> You have to visit `about:config` and set `dom.events.asyncClipboard.clipboardItem` to `true`.
> 
> ![image](https://user-images.githubusercontent.com/36794274/184440553-f5f46dd6-ca52-4dfe-ba88-c1f3555856fb.png)

could you also inform all my users of my site of that procedure? Should I create a UserManual of how to use my site?

**Comment by sdudnic** [comment]
So, it seems there is no univseral solution to copy an image to clipboard. Modifying the settings in Firefox should event not be proposed: any client of the web application is aware of that manipunation to do, so in practice is not a solution.

**Comment by LuanEdCosta** [comment]
For now the only way of copying images on Firefox is setting this flag to true, but obviously you should not ask your users to do that. 

You can still use this library and check if it's possible to copy to clipboard or not using the `canCopyImagesToClipboard` function ([example from docs](https://github.com/LuanEdCosta/copy-image-clipboard#check-if-can-copy-images-to-clipboard)). This way people using browsers that support copying images will have the functionality. 

This library only makes easier copying images to clipboard using browser web API's, it's not my fault that Firefox decided to hide this feature behind a flag.

https://developer.mozilla.org/en-US/docs/Web/API/ClipboardItem#browser_compatibility

**Comment by cozumel424** [comment]
Here https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/clipboard/setImageData

There's very little point writing a package that doesn't work properly, especially when the fix is so trivial.
