### ISSUE TITLE
Uncaught SyntaxError: Unexpected token 'export'

### ISSUE THREAD

**Issue by huanlirui** [LuanEdCosta/copy-image-clipboard#40]
![image](https://user-images.githubusercontent.com/40491203/206078267-26f06fda-d528-4ede-bcc7-acfb08b4fa4c.png)

**Comment by LuanEdCosta** [comment]
**Error:** Your environment does not support EcmaScript Modules (ESM or ES6 Modules).
**Possible solution:** A file with CommonJS modules was published along with this library, maybe using it will solve the problem.

---

Could you show how are you importing the library in your code? So I can help you better.
