### ISSUE TITLE
Demo page not working on latest Mozilla Firefox

### ISSUE THREAD

**Issue by xdung24** [LuanEdCosta/copy-image-clipboard#41]
**Describe the bug**

Code not working on latest Firefox, but works well on Google Chrome/Chromium
The demo url for testing also doesn't work (https://luanedcosta.github.io/copy-image-clipboard/)
I haven't test on older version of Mozilla Firefox

**Browsers (please complete the following information)**

Browser name: Mozilla Firefox
Version: 107.0.1

**Expected behavior**

The demo page as well as the code should work properly

**Screenshots**

<img width="1673" alt="Screen Shot 2022-12-08 at 09 59 00" src="https://user-images.githubusercontent.com/5617222/206345329-9b4e3d79-ec8f-49b8-84a5-4fc0537e8bce.png">

<img width="1645" alt="Screen Shot 2022-12-08 at 09 58 22" src="https://user-images.githubusercontent.com/5617222/206345262-80b3e66c-4e2e-41cb-8154-04d19fd96842.png">

<img width="1629" alt="Screen Shot 2022-12-08 at 09 57 31" src="https://user-images.githubusercontent.com/5617222/206345201-43799433-3c8d-442f-8756-9c3b3aeba825.png">

**Comment by LuanEdCosta** [comment]
Unfortunately this is a Firefox problem. They decided to disable the `ClipboardItem` by default, so we have to enable a flag on Firefox configs to work properly.

![image](https://user-images.githubusercontent.com/36794274/206518034-5d4af0b1-c0d6-48db-8322-f9009ba5dbfa.png)
Print from MDN Docs: https://developer.mozilla.org/en-US/docs/Web/API/ClipboardItem#browser_compatibility

---

The browser ClipboardAPI is a recent feature with many cross-browser compatibility issues.
We should not ask for users to enable this flag. Instead, we can disable the copy button using the `canCopyImagesToClipboard` function from this library.

---

Sorry for the long explanation. I plan to rewrite docs and the demo to explain these details in a better way.
